### PR TITLE
Engine rewrite

### LINKED ISSUE #7: Received unexpected trace event (:gc_minor_start & :gc_minor_end)
Elixir 1.13.3
Phoenix v1.6.6
{:flame_on, "~> 0.3.0"}

image

image

image

(Output filename: flame_on_output_delete_me/1646851436679673-eflambe-output.bggg) I can't find this file

### LINKED ISSUE #9: Flame On does not display result
Hi, I'm testing flame_on on my local server but it doesn't display profiling result and it uses too much memory.

### Dependencies
```
      {:phoenix, "~> 1.6"},
      {:phoenix_ecto, "~> 4.0"},
      {:phoenix_live_dashboard, "~> 0.6.5"},
      {:flame_on, "~> 0.3"},
      {:telemetry_metrics, "~> 0.4"},
      {:telemetry_poller, "~> 0.4"}
```

### Environment
- Macbook M1
- Elixir: 1.13
- Erlang: 24.1.4

**It uses too much memory**
Screen Shot 2022-03-17 at 10 52 01 AM

**Capturing timeout**
Screen Shot 2022-03-17 at 10 46 35 AM

**Some strange output on console**
```
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 144705}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 144706}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :gc_minor_start, [wordsize: 2, old_heap_block_size: 196650, heap_block_size: 28690, mbuf_size: 1168, recent_size: 187, stack_size: 155, old_heap_size: 81714, heap_size: 28534, bin_vheap_size: 105, bin_vheap_block_size: 46422, bin_old_vheap_size: 5583, bin_old_vheap_block_size: 46422], {1647, 489616, 145129}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :gc_minor_end, [wordsize: 28251, old_heap_block_size: 196650, heap_block_size: 28690, mbuf_size: 0, recent_size: 1354, stack_size: 155, old_heap_size: 81811, heap_size: 1354, bin_vheap_size: 12, bin_vheap_block_size: 46422, bin_old_vheap_size: 5619, bin_old_vheap_block_size: 46422], {1647, 489616, 145130}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 145134}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 145135}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.4454.0>, :return_to, {Jason.Encode, :map_naive_loop, 3}, {1647, 489616, 145136}}
```

Do I miss any configuration to make it work?

Thanks

### LINKED ISSUE #11: Rebuild underlying capture engine
This issue is to notify of and keep track of the upcoming rebuild of the underlying engine that powers Flame On.

Now that a larger number of people are starting to use Flame On, it is becoming apparent that there are issues when dealing with larger datasets. It works great with a basic generated Phoenix app and a basic page, but once you hit a certain size of request, eFlambe fails to complete and we have little or no visibility into, or control over, handling this from the Flame On side of things. This makes debugging or diagnosing the issues difficult or impossible.

Flame On uses eFlambe under the hood in a very brittle hands-off manner, because the design goals of eFlambe and Flame On aren't exactly in sync (eFlambe being designed to generate flamegraph files, and Flame On needing access to the data directly). A more efficient and cleaner approach is to implement the core capture mechanism inside Flame On directly, giving us much more control and visibility into it and any potential issues that arise in the future.

If you like what Flame On is doing, but are one of the ones who find it to simply fail in your use case, hold on, an improved engine is coming... soon™️.

### PR DESCRIPTION
**Pull request by TheFirstAvenger**
This PR fixes #11. It replaces the underlying eFlambe library with a custom engine build from the ground up to meet the specific needs of FlameOn. It removes a number of layers of process and code that were necessary to shoehorn eFlambe into what FlameOn needs, and will give us much better visibility into resolving any outstanding or future issues.

Also fixes #7 and fixes #9.

### CODE REVIEW

File: mix.exs [hunk 1]
```diff
@@ -48,6 +48,7 @@ defmodule FlameOn.MixProject do
       {:ex_doc, "~> 0.28.0", only: :dev, runtime: false},
       {:ecto, "~> 3.7"},
       {:eflambe, "~> 0.2.3"},
```
Comment (bcardarella) [inline mix.exs:50]: is eflamebe still necessary now?

Comment (TheFirstAvenger) [reply mix.exs]: Nope, good catch! Removed.
